# Logic Gates Perceptron representation

**NOR Logic Perceptron**



In [0]:
import tensorflow as tf
import numpy as np

**Define the training example set: **<br>
        True: 1.0 <br>
        False: 0.0 <br>
        bias: 1.0 <br>
**Learning Rate = 0.1**



In [0]:
training_input=tf.Variable([[0.0,0.0,1.0],[1.0,0.0,1.0],[0.0,1.0,1.0],[1.0,1.0,1.0]],dtype=tf.float16) 
training_output=tf.Variable([[1.0],[0.0],[0.0],[0.0]],dtype=tf.float16)
learning_rate=0.1

**Layer 1:**<br>
Weights and bias of the perceptron

In [0]:
and_nn={
    'weights':tf.Variable(tf.random_normal([3,1],dtype=tf.float16))
}

**Testing Data**

In [0]:
testing_input=tf.Variable([[1.0,1.0,1.0],[1.0,1.0,1.0],[0.0,0.0,1.0],[1.0,0.0,1.0]],dtype=tf.float16)
testing_output=tf.Variable([[0.0],[0.0],[1.0],[0.0]],dtype=tf.float16)

test_output=tf.greater(tf.matmul(testing_input,and_nn['weights']),0)

**Activation( input*weight + bias )**

In [0]:
output=tf.sigmoid(tf.matmul(training_input,and_nn['weights'])) 

**Error = Expected Output - Actual Output**

In [0]:
error=training_output-output

**Mean Squared Error = reduce_mean( error^2  )**

In [0]:
mse=tf.reduce_mean(tf.square(error))

**Optimize Cost Function i.e MSE and adjust weights**

In [0]:
delta=tf.matmul(training_input,error,transpose_a=True) #2x1
temp=and_nn['weights']+(learning_rate*delta)
assign_weights=tf.assign(and_nn['weights'],temp)

**Epoch = Forward Propogation + Back Propogation <br> Max epochs = 2000**

In [9]:
max_epochs=2000

sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
for i in range(0,max_epochs):
  sess.run(assign_weights)
print('Final Theta:',sess.run(and_nn['weights']))
print('MSE:',sess.run(mse))

Final Theta: [[-6.89]
 [-6.89]
 [ 2.97]]
MSE: 0.0007734


**Testing**

In [10]:
print('Testing Input: \n',sess.run(testing_input))
print('Output: \n',sess.run(test_output))

Testing Input: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 1.]
 [1. 0. 1.]]
Output: 
 [[False]
 [False]
 [ True]
 [False]]


In [0]:
sess.close()